// Code generated by Slice Machine. DO NOT EDIT.

import Author from './Author/index.svelte';
import Image from './Image/index.svelte';
import Name from './Name/index.svelte';

export const components = {
	author: Author,
	image: Image,
	name: Name
};
